print("i am a student of zenith school of ai")
print("an apple a day keeps doctor away")
print("spider"*10)
print("i am a student of zenith school of ai")
print("an apple a day keeps doctor away")
print("spider"*10)
